INSERT INTO CATEGORIES (NAME) VALUES ('Eletronics')
INSERT INTO PRODUCTS (CATEGORYID, NAME) VALUES (1,'Notebook Acer')
INSERT INTO PRODUCTS (CATEGORYID, NAME) VALUES (1,'Notebook Sony')
INSERT INTO PRODUCTS (CATEGORYID, NAME) VALUES (1,'Notebook Dell')